---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: registry.access.redhat.com/ubi8/ubi-init
    networks:
      - name: "red_prometheus"    
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: nodo1
    image: registry.access.redhat.com/ubi8/ubi-init
    networks:
      - name: "red_prometheus"     
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
  # - name: nodo2
  #   image: registry.access.redhat.com/ubi8/ubi-init
  #   networks:
  #     - name: "red_prometheus"     
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   capabilities:
  #     - SYS_ADMIN
  #   command: "/usr/sbin/init"
  #   pre_build_image: true
  # - name: nodo3
  #   image: registry.access.redhat.com/ubi8/ubi-init
  #   networks:
  #     - name: "red_prometheus"     
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   capabilities:
  #     - SYS_ADMIN
  #   command: "/usr/sbin/init"
  #   pre_build_image: true            
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .

...